version: '3.1'

# does not work atm.
services:
  ledger-docker:
    image: ledger
    ports:
      - 8082:8082
    build: .
    volumes:
      - ledger:/home/runmyaccounts
    command: sudo /usr/sbin/httpd
#    entrypoint: "sudo /usr/sbin/httpd"

volumes:
  ledger: